--------------------------------------------------------
--  File created - Monday-November-09-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence COMBUSTIBLE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MAESTRO"."COMBUSTIBLE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 23 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CONDUCTOR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MAESTRO"."CONDUCTOR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LOG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MAESTRO"."LOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MANTENIMIENTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MAESTRO"."MANTENIMIENTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PLANIFICACION_RUTA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MAESTRO"."PLANIFICACION_RUTA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ROL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MAESTRO"."ROL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 42 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RUTA_CONDUCTOR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MAESTRO"."RUTA_CONDUCTOR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RUTA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MAESTRO"."RUTA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TIPO_MANTENIMIENTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MAESTRO"."TIPO_MANTENIMIENTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USUARIO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MAESTRO"."USUARIO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 123 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence VEHICULO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MAESTRO"."VEHICULO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 22 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table COMBUSTIBLE
--------------------------------------------------------

  CREATE TABLE "MAESTRO"."COMBUSTIBLE" 
   (	"ID_COMBUSTIBLE" NUMBER(15,0), 
	"KINICIAL" NUMBER(15,2), 
	"CANTIDAD" NUMBER(15,4), 
	"PRECIO" NUMBER(15,2), 
	"TIPO" VARCHAR2(20 BYTE), 
	"FACTURA" VARCHAR2(20 BYTE), 
	"PROVEEDOR" VARCHAR2(20 BYTE), 
	"ID_VEHICULO" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401" ;
--------------------------------------------------------
--  DDL for Table CONDUCTOR
--------------------------------------------------------

  CREATE TABLE "MAESTRO"."CONDUCTOR" 
   (	"ID_CONDUCTOR" NUMBER(15,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"CUI" VARCHAR2(20 BYTE), 
	"DIRECCION" VARCHAR2(250 BYTE), 
	"TELEFONO" VARCHAR2(12 BYTE), 
	"FECHA_NAC" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401" ;
--------------------------------------------------------
--  DDL for Table LOG
--------------------------------------------------------

  CREATE TABLE "MAESTRO"."LOG" 
   (	"ID_LOG" NUMBER(15,0), 
	"ID_USUARIO" NUMBER(15,0), 
	"OPERACION" VARCHAR2(20 BYTE), 
	"EN" VARCHAR2(20 BYTE), 
	"DATOS" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401" ;
--------------------------------------------------------
--  DDL for Table MANTENIMIENTO
--------------------------------------------------------

  CREATE TABLE "MAESTRO"."MANTENIMIENTO" 
   (	"ID_MANTENIMIENTO" NUMBER(15,0), 
	"FACTURA" VARCHAR2(20 BYTE), 
	"PROVEEDOR" VARCHAR2(20 BYTE), 
	"FECHA_REPARACION" DATE, 
	"MONTO_REPARACION" NUMBER(15,2), 
	"DESCRIPCION" VARCHAR2(250 BYTE), 
	"ID_VEHICULO" NUMBER(15,0), 
	"ID_TIPO_MANTENIMIENTO" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401" ;
--------------------------------------------------------
--  DDL for Table PLANIFICACION_RUTA
--------------------------------------------------------

  CREATE TABLE "MAESTRO"."PLANIFICACION_RUTA" 
   (	"ID_PLANIFICACION_RUTA" NUMBER(15,0), 
	"NOMBRE" NVARCHAR2(20), 
	"DISTANCIA" NUMBER(15,2), 
	"ID_RUTA" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401" ;
--------------------------------------------------------
--  DDL for Table ROL
--------------------------------------------------------

  CREATE TABLE "MAESTRO"."ROL" 
   (	"ID_ROL" NUMBER(15,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401" ;
--------------------------------------------------------
--  DDL for Table RUTA
--------------------------------------------------------

  CREATE TABLE "MAESTRO"."RUTA" 
   (	"ID_RUTA" NUMBER(15,0), 
	"KILOMETRAJE" NUMBER(15,2), 
	"DESCRIPCION" VARCHAR2(450 BYTE), 
	"NOMBRE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401" ;
--------------------------------------------------------
--  DDL for Table RUTA_CONDUCTOR
--------------------------------------------------------

  CREATE TABLE "MAESTRO"."RUTA_CONDUCTOR" 
   (	"ID_RUTA_CONDUCTOR" NUMBER(15,0), 
	"ID_RUTA" NUMBER(15,0), 
	"ID_CONDUCTOR" NUMBER(15,0), 
	"KILOMETRAJE" NUMBER(15,2), 
	"DESCRIPCION" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401" ;
--------------------------------------------------------
--  DDL for Table TIPO_MANTENIMIENTO
--------------------------------------------------------

  CREATE TABLE "MAESTRO"."TIPO_MANTENIMIENTO" 
   (	"ID_TIPO_MANTENIMIENTO" NUMBER(15,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "MAESTRO"."USUARIO" 
   (	"ID_USUARIO" NUMBER(15,0), 
	"USUARIO" VARCHAR2(20 BYTE), 
	"CONTRASENA" VARCHAR2(50 BYTE), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"TELEFONO" VARCHAR2(12 BYTE), 
	"DIRECCION" VARCHAR2(250 BYTE), 
	"CUI" VARCHAR2(20 BYTE), 
	"FECHA_NAC" DATE, 
	"ID_ROL" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401" ;
--------------------------------------------------------
--  DDL for Table VEHICULO
--------------------------------------------------------

  CREATE TABLE "MAESTRO"."VEHICULO" 
   (	"ID_VEHICULO" NUMBER(15,0), 
	"PLACA" VARCHAR2(10 BYTE), 
	"KILOMETRAJE" NUMBER(15,2), 
	"SERIE" VARCHAR2(50 BYTE), 
	"MOTOR" VARCHAR2(20 BYTE), 
	"ANIO" NUMBER(4,0), 
	"COLOR" VARCHAR2(20 BYTE), 
	"MARCA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401" ;
--------------------------------------------------------
--  DDL for View REPORTE2
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "MAESTRO"."REPORTE2" ("VEHICULO", "ID_VEHICULO", "R_AVG") AS 
  SELECT VEHICULO, ID_VEHICULO, TO_CHAR(AVG(RENDIMIENTO),'9999.99') AS "R_AVG" FROM (SELECT AB.VEHICULO, BA.ID_VEHICULO, ((BA.KINICIAL - AB.KINICIAL)/BA.CANTIDAD) AS "RENDIMIENTO" FROM (
SELECT ID_COMBUSTIBLE, ID_VEHICULO AS "VEHICULO", KINICIAL FROM COMBUSTIBLE WHERE ROWNUM <= ((SELECT COUNT(*) FROM COMBUSTIBLE)-1) ORDER BY ID_COMBUSTIBLE ASC
) AB RIGHT JOIN (
SELECT * FROM 
(SELECT ID_COMBUSTIBLE, ID_VEHICULO, KINICIAL, CANTIDAD FROM COMBUSTIBLE WHERE ROWNUM <= ((SELECT COUNT(*) FROM COMBUSTIBLE)-1) ORDER BY ID_COMBUSTIBLE DESC)
ORDER BY ID_COMBUSTIBLE ASC
) BA ON (AB.VEHICULO = BA.ID_VEHICULO))
WHERE RENDIMIENTO > 0
GROUP BY VEHICULO, ID_VEHICULO
ORDER BY 3 DESC;
REM INSERTING into MAESTRO.COMBUSTIBLE
SET DEFINE OFF;
Insert into MAESTRO.COMBUSTIBLE (ID_COMBUSTIBLE,KINICIAL,CANTIDAD,PRECIO,TIPO,FACTURA,PROVEEDOR,ID_VEHICULO) values (1,100,10,250,'GASOLINA','12547','SHELL',1);
Insert into MAESTRO.COMBUSTIBLE (ID_COMBUSTIBLE,KINICIAL,CANTIDAD,PRECIO,TIPO,FACTURA,PROVEEDOR,ID_VEHICULO) values (2,155,5,125,'GASOLINA','135785','SHELL',1);
Insert into MAESTRO.COMBUSTIBLE (ID_COMBUSTIBLE,KINICIAL,CANTIDAD,PRECIO,TIPO,FACTURA,PROVEEDOR,ID_VEHICULO) values (7,170,5,125,'GASOLINA','135801','SHELL',1);
Insert into MAESTRO.COMBUSTIBLE (ID_COMBUSTIBLE,KINICIAL,CANTIDAD,PRECIO,TIPO,FACTURA,PROVEEDOR,ID_VEHICULO) values (22,200,12,27,'GASOLINA','19851','TEXACO',1);
REM INSERTING into MAESTRO.CONDUCTOR
SET DEFINE OFF;
REM INSERTING into MAESTRO.LOG
SET DEFINE OFF;
REM INSERTING into MAESTRO.MANTENIMIENTO
SET DEFINE OFF;
Insert into MAESTRO.MANTENIMIENTO (ID_MANTENIMIENTO,FACTURA,PROVEEDOR,FECHA_REPARACION,MONTO_REPARACION,DESCRIPCION,ID_VEHICULO,ID_TIPO_MANTENIMIENTO) values (2,'15225','EL TALLER',to_date('15-OCT-15','DD-MON-RR'),1600,'No hay gran cosa que decir',1,'Servicio Menor');
REM INSERTING into MAESTRO.PLANIFICACION_RUTA
SET DEFINE OFF;
REM INSERTING into MAESTRO.ROL
SET DEFINE OFF;
Insert into MAESTRO.ROL (ID_ROL,NOMBRE,DESCRIPCION) values (22,'Conductor',null);
Insert into MAESTRO.ROL (ID_ROL,NOMBRE,DESCRIPCION) values (1,'root',null);
Insert into MAESTRO.ROL (ID_ROL,NOMBRE,DESCRIPCION) values (2,'mantenmiento',null);
Insert into MAESTRO.ROL (ID_ROL,NOMBRE,DESCRIPCION) values (3,'combustible',null);
Insert into MAESTRO.ROL (ID_ROL,NOMBRE,DESCRIPCION) values (4,'ruta',null);
Insert into MAESTRO.ROL (ID_ROL,NOMBRE,DESCRIPCION) values (5,'vehiculo',null);
REM INSERTING into MAESTRO.RUTA
SET DEFINE OFF;
Insert into MAESTRO.RUTA (ID_RUTA,KILOMETRAJE,DESCRIPCION,NOMBRE) values (1,100,'Esta es una prueba. Modificado','Ruta1');
REM INSERTING into MAESTRO.RUTA_CONDUCTOR
SET DEFINE OFF;
Insert into MAESTRO.RUTA_CONDUCTOR (ID_RUTA_CONDUCTOR,ID_RUTA,ID_CONDUCTOR,KILOMETRAJE,DESCRIPCION) values (21,1,105,100,'No tengo comentarios											');
REM INSERTING into MAESTRO.TIPO_MANTENIMIENTO
SET DEFINE OFF;
Insert into MAESTRO.TIPO_MANTENIMIENTO (ID_TIPO_MANTENIMIENTO,NOMBRE,DESCRIPCION) values (1,'Servicio Mayor',null);
Insert into MAESTRO.TIPO_MANTENIMIENTO (ID_TIPO_MANTENIMIENTO,NOMBRE,DESCRIPCION) values (3,'Limpieza de Inyectores',null);
Insert into MAESTRO.TIPO_MANTENIMIENTO (ID_TIPO_MANTENIMIENTO,NOMBRE,DESCRIPCION) values (4,'Reparacion de Muleta',null);
Insert into MAESTRO.TIPO_MANTENIMIENTO (ID_TIPO_MANTENIMIENTO,NOMBRE,DESCRIPCION) values (5,'Pinchazo',null);
Insert into MAESTRO.TIPO_MANTENIMIENTO (ID_TIPO_MANTENIMIENTO,NOMBRE,DESCRIPCION) values (2,'Servicio Menor',null);
REM INSERTING into MAESTRO.USUARIO
SET DEFINE OFF;
Insert into MAESTRO.USUARIO (ID_USUARIO,USUARIO,CONTRASENA,NOMBRE,TELEFONO,DIRECCION,CUI,FECHA_NAC,ID_ROL) values (63,'Usuario3','asdf','Usuario3','Usuario3','Usuario3','Usuario3',to_date('10-MAY-90','DD-MON-RR'),2);
Insert into MAESTRO.USUARIO (ID_USUARIO,USUARIO,CONTRASENA,NOMBRE,TELEFONO,DIRECCION,CUI,FECHA_NAC,ID_ROL) values (105,'Conductor1','asdf','Conductor1','Conductor1','Conductor1','Conductor1',to_date('15-MAY-80','DD-MON-RR'),22);
Insert into MAESTRO.USUARIO (ID_USUARIO,USUARIO,CONTRASENA,NOMBRE,TELEFONO,DIRECCION,CUI,FECHA_NAC,ID_ROL) values (2,'root','root','root','root','root','root',to_date('05-NOV-15','DD-MON-RR'),1);
Insert into MAESTRO.USUARIO (ID_USUARIO,USUARIO,CONTRASENA,NOMBRE,TELEFONO,DIRECCION,CUI,FECHA_NAC,ID_ROL) values (83,'Usuario4','asdf','Usuario4','Usuario4','Usuario4','Usuario4',to_date('01-OCT-95','DD-MON-RR'),4);
Insert into MAESTRO.USUARIO (ID_USUARIO,USUARIO,CONTRASENA,NOMBRE,TELEFONO,DIRECCION,CUI,FECHA_NAC,ID_ROL) values (27,'Usuario1','asdf','Usuario1','Telefono1','Direccion1','CUI1',to_date('24-OCT-95','DD-MON-RR'),5);
Insert into MAESTRO.USUARIO (ID_USUARIO,USUARIO,CONTRASENA,NOMBRE,TELEFONO,DIRECCION,CUI,FECHA_NAC,ID_ROL) values (43,'Usuario2','asdf','Usuario2','Usuario2','Usuario2','Usuario2',to_date('15-MAY-90','DD-MON-RR'),3);
REM INSERTING into MAESTRO.VEHICULO
SET DEFINE OFF;
Insert into MAESTRO.VEHICULO (ID_VEHICULO,PLACA,KILOMETRAJE,SERIE,MOTOR,ANIO,COLOR,MARCA) values (1,'PS-025306',200,'256483','14578413',2014,'ROJO','TOYOTA');
--------------------------------------------------------
--  DDL for Index LOG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAESTRO"."LOG_PK" ON "MAESTRO"."LOG" ("ID_LOG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401" ;
--------------------------------------------------------
--  DDL for Index CONDUCTOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAESTRO"."CONDUCTOR_PK" ON "MAESTRO"."CONDUCTOR" ("ID_CONDUCTOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401" ;
--------------------------------------------------------
--  DDL for Index USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAESTRO"."USUARIO_PK" ON "MAESTRO"."USUARIO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401" ;
--------------------------------------------------------
--  DDL for Index COMBUSTIBLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAESTRO"."COMBUSTIBLE_PK" ON "MAESTRO"."COMBUSTIBLE" ("ID_COMBUSTIBLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401" ;
--------------------------------------------------------
--  DDL for Index MANTENIMIENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAESTRO"."MANTENIMIENTO_PK" ON "MAESTRO"."MANTENIMIENTO" ("ID_MANTENIMIENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401" ;
--------------------------------------------------------
--  DDL for Index RUTA_CONDUCTOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAESTRO"."RUTA_CONDUCTOR_PK" ON "MAESTRO"."RUTA_CONDUCTOR" ("ID_RUTA_CONDUCTOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401" ;
--------------------------------------------------------
--  DDL for Index ROL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAESTRO"."ROL_PK" ON "MAESTRO"."ROL" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401" ;
--------------------------------------------------------
--  DDL for Index PLANIFICACION_RUTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAESTRO"."PLANIFICACION_RUTA_PK" ON "MAESTRO"."PLANIFICACION_RUTA" ("ID_PLANIFICACION_RUTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401" ;
--------------------------------------------------------
--  DDL for Index RUTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAESTRO"."RUTA_PK" ON "MAESTRO"."RUTA" ("ID_RUTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401" ;
--------------------------------------------------------
--  DDL for Index VEHICULO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAESTRO"."VEHICULO_PK" ON "MAESTRO"."VEHICULO" ("ID_VEHICULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401" ;
--------------------------------------------------------
--  DDL for Index TIPO_MANTENIMIENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAESTRO"."TIPO_MANTENIMIENTO_PK" ON "MAESTRO"."TIPO_MANTENIMIENTO" ("ID_TIPO_MANTENIMIENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401" ;
--------------------------------------------------------
--  Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "MAESTRO"."ROL" ADD CONSTRAINT "ROL_PK" PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401"  ENABLE;
  ALTER TABLE "MAESTRO"."ROL" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."ROL" MODIFY ("ID_ROL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_MANTENIMIENTO
--------------------------------------------------------

  ALTER TABLE "MAESTRO"."TIPO_MANTENIMIENTO" ADD CONSTRAINT "TIPO_MANTENIMIENTO_PK" PRIMARY KEY ("ID_TIPO_MANTENIMIENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401"  ENABLE;
  ALTER TABLE "MAESTRO"."TIPO_MANTENIMIENTO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."TIPO_MANTENIMIENTO" MODIFY ("ID_TIPO_MANTENIMIENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VEHICULO
--------------------------------------------------------

  ALTER TABLE "MAESTRO"."VEHICULO" ADD CONSTRAINT "VEHICULO_PK" PRIMARY KEY ("ID_VEHICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401"  ENABLE;
  ALTER TABLE "MAESTRO"."VEHICULO" MODIFY ("MARCA" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."VEHICULO" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."VEHICULO" MODIFY ("ANIO" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."VEHICULO" MODIFY ("KILOMETRAJE" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."VEHICULO" MODIFY ("PLACA" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."VEHICULO" MODIFY ("ID_VEHICULO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RUTA_CONDUCTOR
--------------------------------------------------------

  ALTER TABLE "MAESTRO"."RUTA_CONDUCTOR" ADD CONSTRAINT "RUTA_CONDUCTOR_PK" PRIMARY KEY ("ID_RUTA_CONDUCTOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401"  ENABLE;
  ALTER TABLE "MAESTRO"."RUTA_CONDUCTOR" MODIFY ("KILOMETRAJE" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."RUTA_CONDUCTOR" MODIFY ("ID_CONDUCTOR" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."RUTA_CONDUCTOR" MODIFY ("ID_RUTA" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."RUTA_CONDUCTOR" MODIFY ("ID_RUTA_CONDUCTOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MANTENIMIENTO
--------------------------------------------------------

  ALTER TABLE "MAESTRO"."MANTENIMIENTO" ADD CONSTRAINT "MANTENIMIENTO_PK" PRIMARY KEY ("ID_MANTENIMIENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401"  ENABLE;
  ALTER TABLE "MAESTRO"."MANTENIMIENTO" MODIFY ("ID_TIPO_MANTENIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."MANTENIMIENTO" MODIFY ("ID_VEHICULO" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."MANTENIMIENTO" MODIFY ("MONTO_REPARACION" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."MANTENIMIENTO" MODIFY ("FECHA_REPARACION" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."MANTENIMIENTO" MODIFY ("PROVEEDOR" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."MANTENIMIENTO" MODIFY ("FACTURA" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."MANTENIMIENTO" MODIFY ("ID_MANTENIMIENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLANIFICACION_RUTA
--------------------------------------------------------

  ALTER TABLE "MAESTRO"."PLANIFICACION_RUTA" ADD CONSTRAINT "PLANIFICACION_RUTA_PK" PRIMARY KEY ("ID_PLANIFICACION_RUTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401"  ENABLE;
  ALTER TABLE "MAESTRO"."PLANIFICACION_RUTA" MODIFY ("ID_RUTA" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."PLANIFICACION_RUTA" MODIFY ("DISTANCIA" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."PLANIFICACION_RUTA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."PLANIFICACION_RUTA" MODIFY ("ID_PLANIFICACION_RUTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "MAESTRO"."USUARIO" ADD CONSTRAINT "USUARIO_PK" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401"  ENABLE;
  ALTER TABLE "MAESTRO"."USUARIO" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."USUARIO" MODIFY ("FECHA_NAC" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."USUARIO" MODIFY ("CUI" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."USUARIO" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."USUARIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."USUARIO" MODIFY ("CONTRASENA" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."USUARIO" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMBUSTIBLE
--------------------------------------------------------

  ALTER TABLE "MAESTRO"."COMBUSTIBLE" ADD CONSTRAINT "COMBUSTIBLE_PK" PRIMARY KEY ("ID_COMBUSTIBLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401"  ENABLE;
  ALTER TABLE "MAESTRO"."COMBUSTIBLE" MODIFY ("ID_VEHICULO" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."COMBUSTIBLE" MODIFY ("PROVEEDOR" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."COMBUSTIBLE" MODIFY ("FACTURA" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."COMBUSTIBLE" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."COMBUSTIBLE" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."COMBUSTIBLE" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."COMBUSTIBLE" MODIFY ("KINICIAL" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."COMBUSTIBLE" MODIFY ("ID_COMBUSTIBLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RUTA
--------------------------------------------------------

  ALTER TABLE "MAESTRO"."RUTA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."RUTA" ADD CONSTRAINT "RUTA_PK" PRIMARY KEY ("ID_RUTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401"  ENABLE;
  ALTER TABLE "MAESTRO"."RUTA" MODIFY ("KILOMETRAJE" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."RUTA" MODIFY ("ID_RUTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONDUCTOR
--------------------------------------------------------

  ALTER TABLE "MAESTRO"."CONDUCTOR" ADD CONSTRAINT "CONDUCTOR_PK" PRIMARY KEY ("ID_CONDUCTOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401"  ENABLE;
  ALTER TABLE "MAESTRO"."CONDUCTOR" MODIFY ("FECHA_NAC" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."CONDUCTOR" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."CONDUCTOR" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."CONDUCTOR" MODIFY ("CUI" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."CONDUCTOR" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."CONDUCTOR" MODIFY ("ID_CONDUCTOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOG
--------------------------------------------------------

  ALTER TABLE "MAESTRO"."LOG" ADD CONSTRAINT "LOG_PK" PRIMARY KEY ("ID_LOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_4774828552099401"  ENABLE;
  ALTER TABLE "MAESTRO"."LOG" MODIFY ("EN" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."LOG" MODIFY ("OPERACION" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."LOG" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "MAESTRO"."LOG" MODIFY ("ID_LOG" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COMBUSTIBLE
--------------------------------------------------------

  ALTER TABLE "MAESTRO"."COMBUSTIBLE" ADD CONSTRAINT "COMBUSTIBLE_FK" FOREIGN KEY ("ID_VEHICULO")
	  REFERENCES "MAESTRO"."VEHICULO" ("ID_VEHICULO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOG
--------------------------------------------------------

  ALTER TABLE "MAESTRO"."LOG" ADD CONSTRAINT "LOG_FK" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "MAESTRO"."USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MANTENIMIENTO
--------------------------------------------------------

  ALTER TABLE "MAESTRO"."MANTENIMIENTO" ADD CONSTRAINT "MANTENIMIENTO_FK" FOREIGN KEY ("ID_VEHICULO")
	  REFERENCES "MAESTRO"."VEHICULO" ("ID_VEHICULO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLANIFICACION_RUTA
--------------------------------------------------------

  ALTER TABLE "MAESTRO"."PLANIFICACION_RUTA" ADD CONSTRAINT "PLANIFICACION_RUTA_FK" FOREIGN KEY ("ID_RUTA")
	  REFERENCES "MAESTRO"."RUTA" ("ID_RUTA") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RUTA_CONDUCTOR
--------------------------------------------------------

  ALTER TABLE "MAESTRO"."RUTA_CONDUCTOR" ADD CONSTRAINT "RUTA_CONDUCTOR_FK" FOREIGN KEY ("ID_RUTA")
	  REFERENCES "MAESTRO"."RUTA" ("ID_RUTA") ENABLE;
  ALTER TABLE "MAESTRO"."RUTA_CONDUCTOR" ADD CONSTRAINT "RUTA_CONDUCTOR_FK2" FOREIGN KEY ("ID_CONDUCTOR")
	  REFERENCES "MAESTRO"."USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "MAESTRO"."USUARIO" ADD CONSTRAINT "USUARIO_FK" FOREIGN KEY ("ID_ROL")
	  REFERENCES "MAESTRO"."ROL" ("ID_ROL") ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_COMBUSTIBLE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MAESTRO"."BI_COMBUSTIBLE" 
  before insert on "COMBUSTIBLE"               
  for each row  
begin   
  if :NEW."ID_COMBUSTIBLE" is null then 
    select "COMBUSTIBLE_SEQ".nextval into :NEW."ID_COMBUSTIBLE" from dual; 
  end if; 
end; 

/
ALTER TRIGGER "MAESTRO"."BI_COMBUSTIBLE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_CONDUCTOR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MAESTRO"."BI_CONDUCTOR" 
  before insert on "CONDUCTOR"               
  for each row  
begin   
  if :NEW."ID_CONDUCTOR" is null then 
    select "CONDUCTOR_SEQ".nextval into :NEW."ID_CONDUCTOR" from dual; 
  end if; 
end; 

/
ALTER TRIGGER "MAESTRO"."BI_CONDUCTOR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_LOG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MAESTRO"."BI_LOG" 
  before insert on "LOG"               
  for each row  
begin   
  if :NEW."ID_LOG" is null then 
    select "LOG_SEQ".nextval into :NEW."ID_LOG" from dual; 
  end if; 
end; 

/
ALTER TRIGGER "MAESTRO"."BI_LOG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_MANTENIMIENTO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MAESTRO"."BI_MANTENIMIENTO" 
  before insert on "MANTENIMIENTO"               
  for each row  
begin   
  if :NEW."ID_MANTENIMIENTO" is null then 
    select "MANTENIMIENTO_SEQ".nextval into :NEW."ID_MANTENIMIENTO" from dual; 
  end if; 
end; 

/
ALTER TRIGGER "MAESTRO"."BI_MANTENIMIENTO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_PLANIFICACION_RUTA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MAESTRO"."BI_PLANIFICACION_RUTA" 
  before insert on "PLANIFICACION_RUTA"               
  for each row  
begin   
  if :NEW."ID_PLANIFICACION_RUTA" is null then 
    select "PLANIFICACION_RUTA_SEQ".nextval into :NEW."ID_PLANIFICACION_RUTA" from dual; 
  end if; 
end; 

/
ALTER TRIGGER "MAESTRO"."BI_PLANIFICACION_RUTA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_ROL
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MAESTRO"."BI_ROL" 
  before insert on "ROL"               
  for each row  
begin   
  if :NEW."ID_ROL" is null then 
    select "ROL_SEQ".nextval into :NEW."ID_ROL" from dual; 
  end if; 
end; 

/
ALTER TRIGGER "MAESTRO"."BI_ROL" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_RUTA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MAESTRO"."BI_RUTA" 
  before insert on "RUTA"               
  for each row  
begin   
  if :NEW."ID_RUTA" is null then 
    select "RUTA_SEQ".nextval into :NEW."ID_RUTA" from dual; 
  end if; 
end; 

/
ALTER TRIGGER "MAESTRO"."BI_RUTA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_RUTA_CONDUCTOR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MAESTRO"."BI_RUTA_CONDUCTOR" 
  before insert on "RUTA_CONDUCTOR"               
  for each row  
begin   
  if :NEW."ID_RUTA_CONDUCTOR" is null then 
    select "RUTA_CONDUCTOR_SEQ".nextval into :NEW."ID_RUTA_CONDUCTOR" from dual; 
  end if; 
end; 

/
ALTER TRIGGER "MAESTRO"."BI_RUTA_CONDUCTOR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_TIPO_MANTENIMIENTO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MAESTRO"."BI_TIPO_MANTENIMIENTO" 
  before insert on "TIPO_MANTENIMIENTO"               
  for each row  
begin   
  if :NEW."ID_TIPO_MANTENIMIENTO" is null then 
    select "TIPO_MANTENIMIENTO_SEQ".nextval into :NEW."ID_TIPO_MANTENIMIENTO" from dual; 
  end if; 
end; 

/
ALTER TRIGGER "MAESTRO"."BI_TIPO_MANTENIMIENTO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_USUARIO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MAESTRO"."BI_USUARIO" 
  before insert on "USUARIO"               
  for each row  
begin   
  if :NEW."ID_USUARIO" is null then 
    select "USUARIO_SEQ".nextval into :NEW."ID_USUARIO" from dual; 
  end if; 
end; 

/
ALTER TRIGGER "MAESTRO"."BI_USUARIO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_VEHICULO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MAESTRO"."BI_VEHICULO" 
  before insert on "VEHICULO"               
  for each row  
begin   
  if :NEW."ID_VEHICULO" is null then 
    select "VEHICULO_SEQ".nextval into :NEW."ID_VEHICULO" from dual; 
  end if; 
end; 

/
ALTER TRIGGER "MAESTRO"."BI_VEHICULO" ENABLE;
--------------------------------------------------------
--  DDL for Function CUSTOM_AUTH
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "MAESTRO"."CUSTOM_AUTH" (p_username in VARCHAR2, p_password in VARCHAR2)
return BOOLEAN
is
  l_password varchar2(4000);
  l_stored_password varchar2(4000);
  l_expires_on date;
  l_count number;
begin
-- First, check to see if the user is in the user table
select count(*) into l_count from demo_users where user_name = p_username;
if l_count > 0 then
  -- First, we fetch the stored hashed password & expire date
  select password, expires_on into l_stored_password, l_expires_on
   from demo_users where user_name = p_username;

  -- Next, we check to see if the user's account is expired
  -- If it is, return FALSE
  if l_expires_on > sysdate or l_expires_on is null then

    -- If the account is not expired, we have to apply the custom hash
    -- function to the password
    l_password := custom_hash(p_username, p_password);

    -- Finally, we compare them to see if they are the same and return
    -- either TRUE or FALSE
    if l_password = l_stored_password then
      return true;
    else
      return false;
    end if;
  else
    return false;
  end if;
else
  -- The username provided is not in the DEMO_USERS table
  return false;
end if;
end;

/
--------------------------------------------------------
--  DDL for Function CUSTOM_HASH
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "MAESTRO"."CUSTOM_HASH" (p_username in varchar2, p_password in varchar2)
return varchar2
is
  l_password varchar2(4000);
  l_salt varchar2(4000) := 'GBP9621AIFDGPPHU1Z2YRKQLZ5ZIV0';
begin

-- This function should be wrapped, as the hash algorhythm is exposed here.
-- You can change the value of l_salt or the method of which to call the
-- DBMS_OBFUSCATOIN toolkit, but you much reset all of your passwords
-- if you choose to do this.

l_password := utl_raw.cast_to_raw(dbms_obfuscation_toolkit.md5
  (input_string => p_password || substr(l_salt,10,13) || p_username ||
    substr(l_salt, 4,10)));
return l_password;
end;

/
--------------------------------------------------------
--  DDL for Procedure ADDCOMBUSTIBLE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."ADDCOMBUSTIBLE" 
(p_kinicial IN NUMBER,
p_cantidad IN NUMBER,
p_precio IN NUMBER,
p_tipo IN VARCHAR2,
p_factura IN VARCHAR2,
p_proveedor IN VARCHAR2,
p_vehiculo IN NUMBER)
is
begin
INSERT INTO COMBUSTIBLE
("KINICIAL", "CANTIDAD", "PRECIO", "TIPO", "FACTURA", "PROVEEDOR", "ID_VEHICULO")
VALUES
(p_kinicial, p_cantidad, p_precio, p_tipo, p_factura, p_proveedor, p_vehiculo);
COMMIT;
end;

/
--------------------------------------------------------
--  DDL for Procedure ADDCONDUCTOR
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."ADDCONDUCTOR" 
(p_nombre IN VARCHAR2,
p_cui IN VARCHAR2,
p_direccion IN VARCHAR2,
p_telefono IN VARCHAR2,
p_fechanac IN DATE)
is
begin
INSERT INTO CONDUCTOR ("NOMBRE", "CUI", "DIRECCION", "TELEFONO", "FECHA_NAC")
VALUES (p_nombre, p_cui, p_direccion, p_telefono, p_fechanac);
end;

/
--------------------------------------------------------
--  DDL for Procedure ADDMANTENIMIENTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."ADDMANTENIMIENTO" 
(p_factura IN VARCHAR2,
p_proveedor IN VARCHAR2,
p_fecha IN DATE,
p_monto IN NUMBER,
p_descripcion IN VARCHAR2,
p_vehiculo IN NUMBER,
p_tipo_mantenimiento IN VARCHAR2)
is
begin
INSERT INTO MANTENIMIENTO ("FACTURA", "PROVEEDOR", "FECHA_REPARACION", "MONTO_REPARACION", "DESCRIPCION", "ID_VEHICULO", "ID_TIPO_MANTENIMIENTO")
VALUES (p_factura, p_proveedor, p_fecha, p_monto, p_descripcion, p_vehiculo, p_tipo_mantenimiento);

COMMIT;
end;

/
--------------------------------------------------------
--  DDL for Procedure ADDPLANIFICACION
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."ADDPLANIFICACION" 
(p_nombre IN VARCHAR2,
p_distancia IN NUMBER,
p_id_ruta IN NUMBER)
is
begin
INSERT INTO PLANIFICACION_RUTA ("NOMBRE", "DISTANCIA", "ID_RUTA")
VALUES
(p_nombre, p_distancia, p_id_ruta);

COMMIT;
end;

/
--------------------------------------------------------
--  DDL for Procedure ADDRUTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."ADDRUTA" 
(p_nombre IN VARCHAR2,
p_kilometraje IN NUMBER,
descripcion IN VARCHAR2)
is
begin
INSERT INTO ruta
("KILOMETRAJE", "DESCRIPCION", "NOMBRE")
VALUES
(p_kilometraje, descripcion, p_nombre);
COMMIT;
end;

/
--------------------------------------------------------
--  DDL for Procedure ADDRUTACONDUCTOR
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."ADDRUTACONDUCTOR" 
(p_ruta IN NUMBER,
p_conductor IN NUMBER,
p_kilometraje IN NUMBER,
p_descripcion IN VARCHAR2)
AS
begin
INSERT INTO RUTA_CONDUCTOR
("ID_RUTA", "ID_CONDUCTOR", "KILOMETRAJE", "DESCRIPCION")
VALUES
(p_ruta, p_conductor, p_kilometraje, p_descripcion);
COMMIT;
end;

/
--------------------------------------------------------
--  DDL for Procedure ADDUSUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."ADDUSUARIO" 
(p_usuario IN VARCHAR2,
p_contrasena IN VARCHAR2,
p_nombre IN VARCHAR2,
p_telefono IN VARCHAR2,
p_direccion IN VARCHAR2,
p_cui IN VARCHAR2,
p_fechanac IN DATE,
p_id_rol IN NUMBER)
is
begin
INSERT INTO USUARIO ("USUARIO", "CONTRASENA", "NOMBRE", "TELEFONO", "DIRECCION", "CUI", "FECHA_NAC", "ID_ROL")
    VALUES (p_usuario, p_contrasena, p_nombre, p_telefono, p_direccion, p_cui, TO_DATE(p_fechanac,'DD-MON-YY'), p_id_rol);
COMMIT;
end;

/
--------------------------------------------------------
--  DDL for Procedure ADDVEHICULO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."ADDVEHICULO" (
       p_placa IN VEHICULO.PLACA%TYPE,
       p_kilometraje IN VEHICULO.KILOMETRAJE%TYPE,
       p_serie IN VEHICULO.SERIE%TYPE,
       p_motor IN VEHICULO.MOTOR%TYPE,
     p_anio IN VEHICULO.ANIO%TYPE,
     p_color IN VEHICULO.COLOR%TYPE,
     p_marca IN VEHICULO.MARCA%TYPE)
IS
BEGIN

  INSERT INTO VEHICULO ("PLACA", "KILOMETRAJE", "SERIE", "MOTOR", "ANIO", "COLOR", "MARCA")
  VALUES (p_placa, p_kilometraje, p_serie, p_motor, p_anio, p_color, p_marca);

  COMMIT;

END;

/
--------------------------------------------------------
--  DDL for Procedure DELCOMBUSTIBLE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."DELCOMBUSTIBLE" 
(id IN NUMBER)
is
begin
DELETE FROM COMBUSTIBLE WHERE ID_COMBUSTIBLE = id;
COMMIT;
end;

/
--------------------------------------------------------
--  DDL for Procedure DELCONDUCTOR
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."DELCONDUCTOR" 
(id IN NUMBER)
is
begin
DELETE FROM CONDUCTOR WHERE ID_CONDUCTOR = id;
COMMIT;
end;

/
--------------------------------------------------------
--  DDL for Procedure DELMANTENIMIENTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."DELMANTENIMIENTO" 
(id IN NUMBER)
is
begin
DELETE FROM MANTENIMIENTO WHERE ID_MANTENIMIENTO = id;
COMMIT;
end;

/
--------------------------------------------------------
--  DDL for Procedure DELPLANIFICACION
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."DELPLANIFICACION" 
(id IN NUMBER)
is
begin

DELETE FROM PLANIFICACION_RUTA WHERE ID_PLANIFICACION_RUTA = id;

COMMIT;
end;

/
--------------------------------------------------------
--  DDL for Procedure DELRUTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."DELRUTA" 
(p_id IN NUMBER)
is
begin
DELETE FROM RUTA WHERE ID_RUTA = p_id;
COMMIT;
end;

/
--------------------------------------------------------
--  DDL for Procedure DELRUTACONDUCTOR
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."DELRUTACONDUCTOR" 
(id IN NUMBER)
is
begin
DELETE FROM RUTA_CONDUCTOR WHERE ID_RUTA_CONDUCTOR = id;
COMMIT;
end;

/
--------------------------------------------------------
--  DDL for Procedure DELUSUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."DELUSUARIO" 
(id IN NUMBER)
is
begin
DELETE FROM USUARIO WHERE ID_USUARIO = id;
COMMIT;
end;

/
--------------------------------------------------------
--  DDL for Procedure DELVEHICULO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."DELVEHICULO" 
(id IN NUMBER)
is
begin
DELETE FROM VEHICULO WHERE ID_VEHICULO = id;
COMMIT;
end;

/
--------------------------------------------------------
--  DDL for Procedure GETALLCONDUCTORES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."GETALLCONDUCTORES" (usuarios OUT SYS_REFCURSOR) AS
BEGIN
OPEN usuarios FOR 
  SELECT ID_USUARIO, USUARIO FROM USUARIO WHERE ID_ROL = 22;
END;

/
--------------------------------------------------------
--  DDL for Procedure GETALLFUELS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."GETALLFUELS" (fuels OUT SYS_REFCURSOR) AS
BEGIN
OPEN fuels FOR 
  SELECT ID_COMBUSTIBLE, FACTURA FROM COMBUSTIBLE;
END;

/
--------------------------------------------------------
--  DDL for Procedure GETALLMANTENIMIENTOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."GETALLMANTENIMIENTOS" (mains OUT SYS_REFCURSOR) AS
BEGIN
OPEN mains FOR 
  SELECT ID_MANTENIMIENTO, FACTURA FROM MANTENIMIENTO;
END;

/
--------------------------------------------------------
--  DDL for Procedure GETALLRUTAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."GETALLRUTAS" (rc OUT SYS_REFCURSOR) AS
BEGIN
OPEN rc FOR
  SELECT ID_RUTA, NOMBRE FROM RUTA;
END;

/
--------------------------------------------------------
--  DDL for Procedure GETALLUSERS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."GETALLUSERS" (usuarios OUT SYS_REFCURSOR) AS
BEGIN
OPEN usuarios FOR 
  SELECT ID_USUARIO, USUARIO FROM USUARIO;
END;

/
--------------------------------------------------------
--  DDL for Procedure GETALLVEHICULOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."GETALLVEHICULOS" (vehiculos OUT SYS_REFCURSOR) AS
BEGIN
OPEN vehiculos FOR
  SELECT ID_VEHICULO, PLACA FROM VEHICULO;
END;

/
--------------------------------------------------------
--  DDL for Procedure GETCOMBUSTIBLE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."GETCOMBUSTIBLE" 
(p_id IN NUMBER, comb OUT SYS_REFCURSOR)
as
begin
OPEN comb FOR
  SELECT * FROM COMBUSTIBLE WHERE ID_COMBUSTIBLE = p_id;
end;

/
--------------------------------------------------------
--  DDL for Procedure GETCONDUCTOR
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."GETCONDUCTOR" 
(p_id IN NUMBER, cond OUT SYS_REFCURSOR)
AS
begin
OPEN cond FOR 
  SELECT * FROM CONDUCTOR WHERE ID_CONDUCTOR = p_id;
end;

/
--------------------------------------------------------
--  DDL for Procedure GETMANTENIMIENTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."GETMANTENIMIENTO" 
(p_id IN NUMBER, rc OUT SYS_REFCURSOR)
as
begin
OPEN rc FOR
  SELECT * FROM MANTENIMIENTO WHERE ID_MANTENIMIENTO = p_id;
end;

/
--------------------------------------------------------
--  DDL for Procedure GETPLANIFICACION
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."GETPLANIFICACION" 
(p_id IN NUMBER, p_plan OUT SYS_REFCURSOR)
AS
begin
OPEN p_plan FOR
  SELECT * FROM PLANIFICACION_RUTA WHERE ID_PLANIFICACION_RUTA = p_id;
end;

/
--------------------------------------------------------
--  DDL for Procedure GETRUTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."GETRUTA" 
(p_id IN NUMBER, rut OUT SYS_REFCURSOR)
AS
begin
OPEN rut FOR
  SELECT * FROM RUTA WHERE ID_RUTA = p_id;
end;

/
--------------------------------------------------------
--  DDL for Procedure GETRUTACONDUCTOR
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."GETRUTACONDUCTOR" 
(p_id IN NUMBER, ruta OUT SYS_REFCURSOR)
AS
begin
OPEN ruta FOR
  SELECT * FROM RUTA_CONDUCTOR WHERE ID_RUTA_CONDUCTOR = p_id;
end;

/
--------------------------------------------------------
--  DDL for Procedure GETRUTASCONDUCTOR
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."GETRUTASCONDUCTOR" 
(p_id IN NUMBER, ruta OUT SYS_REFCURSOR)
AS
begin
OPEN ruta FOR
  SELECT * FROM RUTA_CONDUCTOR WHERE ID_CONDUCTOR = p_id;
end;

/
--------------------------------------------------------
--  DDL for Procedure GETUSUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."GETUSUARIO" 
(p_id IN NUMBER, usr OUT SYS_REFCURSOR)
as
begin
OPEN usr FOR
  SELECT * FROM USUARIO WHERE ID_USUARIO = p_id;
end;

/
--------------------------------------------------------
--  DDL for Procedure GETVEHICULO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."GETVEHICULO" 
(p_id IN NUMBER, veh OUT SYS_REFCURSOR)
AS
BEGIN
OPEN veh FOR
  SELECT * FROM VEHICULO WHERE ID_VEHICULO = p_id;
END;

/
--------------------------------------------------------
--  DDL for Procedure LOGIN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."LOGIN" 
(p_usuario IN VARCHAR2,
p_contrasena IN VARCHAR2,
p_id_rol OUT NUMBER,
p_id_usuario OUT NUMBER)
is
CURSOR fila IS SELECT ID_USUARIO, ID_ROL FROM USUARIO WHERE USUARIO = p_usuario AND CONTRASENA = p_contrasena;
begin
OPEN fila;
LOOP
FETCH fila INTO p_id_usuario, p_id_rol;
EXIT WHEN fila%NOTFOUND;
END LOOP;
CLOSE fila;
end;

/
--------------------------------------------------------
--  DDL for Procedure REPORTE1
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."REPORTE1" (fecha1 IN DATE, fecha2 IN DATE, reporte OUT SYS_REFCURSOR) AS
BEGIN
OPEN reporte FOR 
  SELECT * FROM MANTENIMIENTO 
  WHERE FECHA_REPARACION 
  BETWEEN to_date(fecha1,'yyyy-MM-dd')
  AND to_date(fecha2, 'yyyy-MM-dd')
  ORDER BY MONTO_REPARACION DESC;
END;

/
--------------------------------------------------------
--  DDL for Procedure UPDATECOMBUSTIBLE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."UPDATECOMBUSTIBLE" 
(id IN NUMBER,
p_kinicial IN NUMBER,
p_cantidad IN NUMBER,
p_precio IN NUMBER,
p_tipo IN VARCHAR2,
p_factura IN VARCHAR2,
p_proveedor IN VARCHAR2,
p_vehiculo IN NUMBER)
is
begin
UPDATE COMBUSTIBLE SET
KINICIAL = p_kinicial, CANTIDAD = p_cantidad, PRECIO = p_precio, TIPO = p_tipo,
FACTURA = p_factura, PROVEEDOR = p_proveedor, ID_VEHICULO = p_vehiculo
WHERE ID_COMBUSTIBLE = id;
COMMIT;
end;

/
--------------------------------------------------------
--  DDL for Procedure UPDATECONDUCTOR
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."UPDATECONDUCTOR" 
(id IN NUMBER,
p_nombre IN VARCHAR2,
p_cui IN VARCHAR2,
p_direccion IN VARCHAR2,
p_telefono IN VARCHAR2,
p_fechanac IN DATE)
is
begin
UPDATE CONDUCTOR SET
NOMBRE = p_nombre, CUI = p_cui, DIRECCION = p_direccion,
TELEFONO = p_telefono, FECHA_NAC = p_fechanac
WHERE ID_CONDUCTOR = id;
end;

/
--------------------------------------------------------
--  DDL for Procedure UPDATEPLANIFICACION
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."UPDATEPLANIFICACION" 
(id IN NUMBER,
p_nombre IN VARCHAR2,
p_distancia IN NUMBER,
p_id_ruta IN NUMBER)
is
begin

UPDATE PLANIFICACION_RUTA SET "NOMBRE" = p_nombre, "DISTANCIA" = p_distancia, "ID_RUTA" = p_id_ruta
WHERE ID_PLANIFICACION_RUTA = id;

COMMIT;
end;

/
--------------------------------------------------------
--  DDL for Procedure UPDATERUTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."UPDATERUTA" 
(p_id IN NUMBER,
p_nombre IN VARCHAR2,
p_kilometraje IN NUMBER,
p_descripcion IN VARCHAR2)
is
begin
UPDATE RUTA SET KILOMETRAJE = p_kilometraje, DESCRIPCION = p_descripcion, NOMBRE = p_nombre
WHERE ID_RUTA = p_id;
COMMIT;
end;

/
--------------------------------------------------------
--  DDL for Procedure UPDATERUTACONDUCTOR
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."UPDATERUTACONDUCTOR" 
(p_id IN NUMBER,
p_ruta IN NUMBER,
p_conductor IN NUMBER,
p_kilometraje IN NUMBER,
p_descripcion IN VARCHAR2)
is
begin

UPDATE RUTA_CONDUCTOR SET
ID_RUTA = p_ruta, ID_CONDUCTOR = p_conductor,
KILOMETRAJE = p_kilometraje, DESCRIPCION = p_descripcion
WHERE
ID_RUTA_CONDUCTOR = p_id;

COMMIT;
end;

/
--------------------------------------------------------
--  DDL for Procedure UPDATEUSUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."UPDATEUSUARIO" 
(p_id IN NUMBER,
p_usuario IN VARCHAR2,
p_contrasena IN VARCHAR2,
p_nombre IN VARCHAR2,
p_telefono IN VARCHAR2,
p_direccion IN VARCHAR2,
p_cui IN VARCHAR2,
p_fechanac IN DATE,
p_id_rol IN NUMBER)
as
begin
UPDATE USUARIO SET
USUARIO = p_usuario, CONTRASENA = p_contrasena, NOMBRE = p_nombre,
TELEFONO = p_telefono, DIRECCION = p_direccion, CUI = p_cui,
FECHA_NAC = p_fechanac, ID_ROL = p_id_rol
WHERE
ID_USUARIO = p_id;

COMMIT;
end;

/
--------------------------------------------------------
--  DDL for Procedure UPDATEVEHICULO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."UPDATEVEHICULO" (id IN NUMBER,
       p_placa IN VEHICULO.PLACA%TYPE,
       p_kilometraje IN VEHICULO.KILOMETRAJE%TYPE,
       p_serie IN VEHICULO.SERIE%TYPE,
       p_motor IN VEHICULO.MOTOR%TYPE,
     p_anio IN VEHICULO.ANIO%TYPE,
     p_color IN VEHICULO.COLOR%TYPE,
     p_marca IN VEHICULO.MARCA%TYPE)
IS
BEGIN
UPDATE VEHICULO SET "PLACA" = p_placa, "KILOMETRAJE" = p_kilometraje, "SERIE" = p_serie, "MOTOR" = p_motor, "ANIO" = p_anio, "COLOR" = p_color, "MARCA" = p_marca
WHERE ID_VEHICULO = id;

  COMMIT;

END;

/
--------------------------------------------------------
--  DDL for Procedure UPDMANTENIMIENTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "MAESTRO"."UPDMANTENIMIENTO" 
(p_id IN NUMBER,
p_factura IN VARCHAR2,
p_proveedor IN VARCHAR2,
p_fecha IN DATE,
p_monto IN NUMBER,
p_descripcion IN VARCHAR2,
p_vehiculo IN NUMBER,
p_tipo_mantenimiento IN VARCHAR2)
is
begin
UPDATE MANTENIMIENTO SET FACTURA = p_factura, PROVEEDOR = p_proveedor, FECHA_REPARACION = p_fecha, MONTO_REPARACION = p_monto,
DESCRIPCION = p_descripcion, ID_VEHICULO = p_vehiculo, ID_TIPO_MANTENIMIENTO = p_tipo_mantenimiento
WHERE ID_MANTENIMIENTO = p_id;
COMMIT;
end;

/
